-- Up Migration
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN last_synced_at TYPE TIMESTAMPTZ;
ALTER TABLE streaks ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

-- Down Migration
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE users ALTER COLUMN last_synced_at TYPE TIMESTAMP;
ALTER TABLE streaks ALTER COLUMN updated_at TYPE TIMESTAMP;
